name: Call a reusable workflow

on:
  workflow_dispatch:
jobs:
  call-workflow-passing-data:
    permissions:
      contents: read
      pull-requests: write
    uses: Saravanasgit/cicd-templates/.github/workflows/template-workflow.yml@develop
    with:
      config-path: .github/labeler.yml
    secrets:
      token: ${{ secrets.token }}
