name: Use Source Workflow

on:
  workflow_dispatch:
    inputs:
      repo_name:
        description: "Target repo name"
        required: true
      org_name:
        description: "Org or user name"
        required: true

jobs:
  call-template:
    uses: Saravanasgit/cicd-templates/.github/workflows/template-workflow.yml@develop
    with:
      repo_name: ${{ github.event.inputs.repo_name }}
      org_name: ${{ github.event.inputs.org_name }}
    secrets:
      # Use this PAT to allow access to the private source repo
      GITHUB_TOKEN: "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"

